### ISSUE TITLE
Crear representación del fichero properties

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#1]
Crear una clase llama `AppProperties` en el paquete `red.softn.npedidos.configuration` que represente las propiedades
  que empiezan por `app` del fichero `application.properties`.

Luego reemplazar las propiedades usadas en las clases `WebSecurityConfig` y `AppConfig`.

**Comment by juanguirp** [comment]
¡Hola @nmarulo!
¿Puedo colaborarte con este ajuste?
Yo podría añadir una clase de configuración con el nombre que indicas (`AppProperties.java`) e inyectarla en las 2 clases que mencionas (como haces uso de una etiqueta de `Lombok` para inyectar por el constructor, aplicaría lo mismo para esta nueva clase). 
¡Saludos!

**Comment by nmarulo** [comment]
Hola @juanguirp, todo tuyo. 👍

**Comment by juanguirp** [comment]
¡Gracias @nmarulo ! 🤟🏻

He aplicado los cambios que se necesitan para resolver el issue.
Tu servicio fue ejecutado sin problemas y los valores de las propiedades fueron cargadas en el nuevo bean (estos logs no fueron agregados en el PR):
<img width="1243" alt="imagen" src="https://user-images.githubusercontent.com/14912424/193810761-bb071f09-dfb4-40f2-a7fc-1f5441658d7a.png">

Adicional a esto, he añadido unos comentarios en el `application.properties` para agrupar las propiedades por tipo y facilitar la búsqueda visual de las que son creadas por ti. Dejame saber si te sirve este cambio o prefieres que lo deje como estaba previamente:
<img width="582" alt="imagen" src="https://user-images.githubusercontent.com/14912424/193804856-a84c02ee-4ce4-441e-9e55-1ea7d3d1d37a.png">

**Comment by nmarulo** [comment]
Lo he visto brevemente y se ve correcto. 👏
En cuanto tenga un momento lo reviso bien.

Y sobre los comentarios del fichero `application.properties`, me parece genial, muchas gracias. 😄

**Comment by juanguirp** [comment]
Hola!
Acabo de mandar un ajuste en las unitarias 😆
Me hicieron falta un par de `@Import` para utilizar la nueva configuración 😅
Los test unitarios pasan correctamente:
<img width="271" alt="imagen" src="https://user-images.githubusercontent.com/14912424/193818742-7a632cad-4788-40c3-b086-5585878e277a.png">
