### ISSUE TITLE
Crear test básico para la clase TypeDishService

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#10]
- Crear para la siguiente clase, su test correspondiente:
    - `TypeDishService`

Usar como ejemplo el test de la clase `FoodDishService`.

**Comment by 0x61nas** [comment]
Hello @nmarulo I can help, you can assign the issue for me

**Comment by nmarulo** [comment]
Hello @anas-elgarhy 
Yes, of course.

A point to clarify is that it is not necessary to initialize the value of the property of type `List<FoodDish>`, only data of the `TypeDish`.

If there are any doubts, ask whatever you need. 👍
