### ISSUE TITLE
Crear test básico para la clase UserService

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#11]
- Crear para la siguiente clase, su test correspondiente:
    - `UserService`

Usar como ejemplo el test de la clase `FoodDishService`.

**Comment by LoicB** [comment]
Hola

Me gustaría trabajar en esta ebtrada.
Tendría una pregunta, en el UserServiceTestUtil ¿tendría que crear un Usuario con su Id y nombre de usuario, o debería proporcionar más valores?

Gracias

**Comment by nmarulo** [comment]
@LoicB Hola, claro es todo tuyo. 😄

Ahora en relación a tu pregunta, debes establecer un valor a todas las propiedades de los objetos a usar, pero puedes omitir sus relaciones, es decir, no tienes que inicializar `List<Order>`, solo datos del usuario.

Una cosa más, la clase `UserServiceTestUtil` extiende de `CrudServiceTestUtil` que a su vez extiende de `TestUtil`, en esta ultima clase hay métodos (cuyo nombre inicia por `fake`) que hace uso de la librería **datafaker** (https://github.com/datafaker-net/datafaker/), para generar datos aleatorios, si hace falta, por favor, crea los métodos que necesites de `fake` en esta clase.

Si quedan dudas, pregunta lo que necesites. 👍
