### ISSUE TITLE
Crear test básico para la clase MenuService

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#18]
- Crear para la siguiente clase, su test correspondiente:
    - `MenuService`

Usar como ejemplo el test de la clase `FoodDishService`.

**Comment by gabrielrevelo** [comment]
I would like to work on it, please assign it to me.
@nmarulo

**Comment by nmarulo** [comment]
Thank you for your help on issue #7. 😄
As this project is small, I don't have many tasks to delegate, even so, I am creating these issues to help those who are doing the event.
If this week nobody shows up and you are still interested in this issue I will notify you.

**Comment by Medhavi-16** [comment]
Hi @nmarulo I am interested in working on this issue.

**Comment by nmarulo** [comment]
Hi @Medhavi-16 👋
it's all yours.

**Comment by Medhavi-16** [comment]
Hi @nmarulo , PR here: https://github.com/npedidos/rest-api/pull/25. PTAL.
