### ISSUE TITLE
Error en el encoding al leer un valor del fichero properties

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#2]
Al obtener del fichero `application.properties` el valor de la propiedad `app.description`, debido al encoding del fichero el texto no se muestra correctamente.

En la clase `AppConfig` se puede ver este problema en la propiedad `appDescription`
![image](https://user-images.githubusercontent.com/3668825/193435669-a5a2fdcc-8eb1-4f5f-bed5-88161a5d3c6c.png)

**Comment by chinmaym07** [comment]
Can I work on this @nmarulo .?
I think i will get resolved by adding `PropertySource` annotation with encoding parameter in the `AppConfig` file.

**Comment by nmarulo** [comment]
Hello @chinmaym07, thank you for your help on issue #3. 😄
As this project is small, I don't have many tasks to delegate, even so, I am creating these issues to help those who are doing the event.
If this week nobody shows up and you are still interested in this issue I will notify you.

**Comment by chinmaym07** [comment]
Great to hear that @nmarulo . 💯  🥇 
I was just trying my hands on this.
No worries. I'll let it be available for somebody else to approach it.
Although you gave me the chance to work on #3. Thankyou for that. 🙌🏻 😃

**Comment by nmarulo** [comment]
Thanks to you for your interest and help. 😄

**Comment by nmarulo** [comment]
Hi @chinmaym07, if you are still interested, you can make this issue. 👌

**Comment by chinmaym07** [comment]
Done @nmarulo. Thankyou 🙌🏻 💯 .
Please review.
