### ISSUE TITLE
Registrar adaptador LocalDateTime para Gson

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#20]
Hay que registrar en la clase `GsonConfig` un nuevo `TypeAdapter` de tipo `LocalDateTime`.
Usar como ejemplo el `TypeAdapter` que se registro para el tipo `LocalDate`.

**Comment by davidwillianx** [comment]
Can I get this one ?

**Comment by nmarulo** [comment]
Hello @davidwillianx 👋
Of course
