### ISSUE TITLE
Crear test básico para el método "findAllPageable"

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#21]
Crear un test similar al del método `findAll`, en la clase `CrudServiceTest`.

En la clase `CrudServiceTestUtil` será necesario crear un propiedad de tipo `Page<T>`.

Preguntar cualquier duda.

**Comment by s-aLman** [comment]
@nmarulo I would like to work on this. Could you please assign this to me? 🙂

**Comment by nmarulo** [comment]
Hello @s-aLman 👋
Of course.

**Comment by s-aLman** [comment]
Apologies. Got busy with some other task.

**Comment by nmarulo** [comment]
Ok, no problem, thanks for the intention.
