### ISSUE TITLE
CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Sowham-3098** [npedidos/rest-api#23]
I want to add this.\
Can I add this?

**Comment by nmarulo** [comment]
Hello @Sowham-3098 👋

Ok, sounds good to me.
But I would need the spanish version as the main one and the english version in the "translations" folder. Same as `readme.md`.

**Comment by Sowham-3098** [comment]
Ok! I will try this and make a PR.

**Comment by nmarulo** [comment]
@Sowham-3098  please confirm if you are still interested in working on this assignment, thank you.

**Comment by Sowham-3098** [comment]
Yeah ! I will do it by tomorrow. Sorry for late.
