### ISSUE TITLE
Add OpenAPI documentation + SwaggerUI to the project

### ISSUE THREAD

**Issue by naXa777** [npedidos/rest-api#27]
I propose to add the API documentation generated on the fly based on your Spring controller definitions.
It will look similar to this demo project -> https://petstore.swagger.io/
I can do this myself using `springdoc-openapi-ui` plugin. Please assign this issue to me.

**Comment by nmarulo** [comment]
Hello @naXa777 👋, thank you for your interest in the project.

A basic swagger implementation is already available.

![image](https://user-images.githubusercontent.com/3668825/195987146-08382ef9-10c1-48d4-ab95-ada95b0f02d4.png)

**Comment by naXa777** [comment]
Cool! I noticed the docs later, after I created this issue. Let's close it then.
