### ISSUE TITLE
Crear test básico para la clase FoodDishController

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#28]
Crear para la siguiente clase, su test correspondiente:

- `FoodDishController`

Usar como ejemplo el test de la clase `ExcludeDayController`.

- `ExcludeDayControllerTest`
- `ExcludeDayControllerTestUtil`

De ser necesario crear los métodos **fake** que hagan falta en la clase `TestUtil`.

Si hay dudas, preguntar.

**Comment by LoicB** [comment]
Hola,
¿Puedo ayudar en esta tarea, por favor?

**Comment by nmarulo** [comment]
Hola @LoicB 👋, si, no hay problema.
