### ISSUE TITLE
Crear test básico para la clase MenuController

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#29]
Crear para la siguiente clase, su test correspondiente:

- `MenuController`

Usar como ejemplo el test de la clase `ExcludeDayController`.

- `ExcludeDayControllerTest`
- `ExcludeDayControllerTestUtil`

De ser necesario crear los métodos **fake** que hagan falta en la clase `TestUtil`.

Si hay dudas, preguntar.

**Comment by Quenrelia** [comment]
Hello, 
I would like to try to implement the test if that's ok with you? Thanks!

**Comment by nmarulo** [comment]
Hello @Quenrelia 👋

Yes, of course.
