### ISSUE TITLE
Crear test básico para la clase OrderController

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#30]
Crear para la siguiente clase, su test correspondiente:

- `OrderController`

Usar como ejemplo el test de la clase `ExcludeDayController`.

- `ExcludeDayControllerTest`
- `ExcludeDayControllerTestUtil`

De ser necesario crear los métodos **fake** que hagan falta en la clase `TestUtil`.

Si hay dudas, preguntar.

**Comment by rupeshpurum** [comment]
Hi @nmarulo,
I would like to work on this under hacktoberfest. Could you please assign this to me?

**Comment by nmarulo** [comment]
Hi @rupeshpurum 👋
Yes, of course.

**Comment by nmarulo** [comment]
@rupeshpurum please confirm if you are still interested in working on this assignment, thank you.

**Comment by rupeshpurum** [comment]
@nmarulo, yes I am still interested in solving the issue.
