### ISSUE TITLE
Crear test básico para la clase SettingController

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#31]
Crear para la siguiente clase, su test correspondiente:

- `SettingController`

Usar como ejemplo el test de la clase `ExcludeDayController`.

- `ExcludeDayControllerTest`
- `ExcludeDayControllerTestUtil`

De ser necesario crear los métodos **fake** que hagan falta en la clase `TestUtil`.

Si hay dudas, preguntar.

**Comment by rupeshpurum** [comment]
Hi @nmarulo , 
I would like to work on this under hacktoberfest. Could you please assign this to me?

**Comment by nmarulo** [comment]
Hi @rupeshpurum 👋
As this project is small, I don't have many tasks to delegate, even so, I am creating these issues to help those who are doing the event.
Issues noted as "good first issues" are assigned to only one person per week.

**Comment by Quenrelia** [comment]
Hello, could I work on this issue, please?

**Comment by nmarulo** [comment]
Hello @Quenrelia 👋
Ok, no problem.

**Comment by nmarulo** [comment]
@Quenrelia please confirm if you are still interested in working on this assignment, thank you.

**Comment by Quenrelia** [comment]
@nmarulo yes, sorry, I will create a PR today or tomorrow.
