### ISSUE TITLE
Crear test básico para la clase TypeDishController

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#32]
Crear para la siguiente clase, su test correspondiente:

- `TypeDishController`

Usar como ejemplo el test de la clase `ExcludeDayController`.

- `ExcludeDayControllerTest`
- `ExcludeDayControllerTestUtil`

De ser necesario crear los métodos **fake** que hagan falta en la clase `TestUtil`.

Si hay dudas, preguntar.

**Comment by rupeshpurum** [comment]
Hi @nmarulo ,
I would like to work on this one under Hacktoberfest2022. Could you please assign this to me?

**Comment by nmarulo** [comment]
I answered you here. https://github.com/npedidos/rest-api/issues/31#issuecomment-1283506850

**Comment by LoicB** [comment]
Hola,
¿Puedo ayudar en esta tarea, por favor?

**Comment by nmarulo** [comment]
Hola @LoicB 👋
Ok.
