### ISSUE TITLE
Crear test básico para la clase UserController

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#33]
Crear para la siguiente clase, su test correspondiente:

- `UserController`

Usar como ejemplo el test de la clase `ExcludeDayController`.

- `ExcludeDayControllerTest`
- `ExcludeDayControllerTestUtil`

De ser necesario crear los métodos **fake** que hagan falta en la clase `TestUtil`.

Si hay dudas, preguntar.

**Comment by csgeeek** [comment]
Hey @nmarulo . I would like to work on this issue under hacktoberfest. Can you please assign this to me?

**Comment by nmarulo** [comment]
Hello @Yaswanth820 👋

Yes, of course.
