### ISSUE TITLE
Broken links in README.en.md

### ISSUE THREAD

**Issue by naXa777** [npedidos/rest-api#35]
LICENSE and CONTRIBUTING lead to 404 page.
it's easy to fix. assign to me please.

**Comment by nmarulo** [comment]
Ok, thank you very much.

Please could you also add, in that same PR, the links to the new index I create after the "Local Deployment" heading. ffbc0d7744327494568009a8b1d4f3e9db3bc7e7

**Comment by naXa777** [comment]
ok, a bit later today I'll do this.
