### ISSUE TITLE
Dockerize Spring Boot app

### ISSUE THREAD

**Issue by naXa777** [npedidos/rest-api#36]
Let's create Dockerfile and Docker compose file for your application.
I hope that this change will simplify project setup (goal: a single command to build, run, seed test data in db, everything you need)
and also simplify project deployment to any cloud service that supports Docker.
also Docker is a solution to the well-known problem, when project works fine on a developer's machine, but unexpectedly breaks in a new environment.

please assign me.

**Comment by nmarulo** [comment]
Ok, sounds great, thanks
