### ISSUE TITLE
Add English translation

### ISSUE THREAD

**Issue by Lumary2** [npedidos/rest-api#5]
If you like I can add English translations to your readme and contribution guideline. I think its always great to have more people able to understand your project. :)

**Comment by nmarulo** [comment]
Hello 👋, thanks for your suggestion.
I have yet to finish writing the readme, after that, if I could consider adding a translation.
If you are interested, I could notify you when it is ready to translate.

**Comment by Lumary2** [comment]
Hi sure, feel free to notify me. I don't speak Spanish though and would use goggle translate & check a bit if the grammar makes sense.

**Comment by nmarulo** [comment]
Hello @Lumary2, if you are still interested, can you do the translation, please?
There is no problem using a translator like **google** or **deepl**. 👌

**Comment by Lumary2** [comment]
Hi Nicolas, great, I just opened a PR with the translation. :-)

**Comment by 0x61nas** [comment]
Hi @nmarulo I can translate it into the Arabic language also, if you want

**Comment by nmarulo** [comment]
Hello @anas-elgarhy , thank you very much for your help in the issues #10. 🙌
As for your proposal, for the moment I do not consider necessary another translation because the project is still very small, if the project grows, in the future I could consider it, but thanks anyway.

**Comment by 0x61nas** [comment]
Welcome, @nmarulo ❤️
