### ISSUE TITLE
Nueva entidad Menu

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#7]
- Crear las clases, en su paquete correspondiente:
    - `MenuRequest`
    - `MenuResponse`
    - `MenuController`
    - `MenuService`
    - `MenuRepository`

> No hay que crear la entidad Menú, esta ya fue creada.

Ver las clases de `FoodDish` para tener una referencia. (`FoodDishRequest`, `FoodDishController`, etc...)

**Comment by gabrielrevelo** [comment]
I can work on this, you can assign it to me.

**Comment by nmarulo** [comment]
Hello @GaRev98 👋
Yes, of course.

**Comment by gabrielrevelo** [comment]
Please review : #16 
@nmarulo

**Comment by nmarulo** [comment]
Thank you very much, I will check it as soon as I can.
