### ISSUE TITLE
Crear test básico para la clase OrderService

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#8]
- Crear para la siguiente clase, su test correspondiente:
    - `OrderService`

Usar como ejemplo el test de la clase `FoodDishService`.

**Comment by vaibhavg20comp** [comment]
hey can you explain this issue in English please

**Comment by nmarulo** [comment]
Hello @vaibhavg20comp 👋
Of course, what you need to do is to create the basic unit test class for the `OrderService` class.
There is already a unit test for the `FoodDishService` class, so you can rely on its classes (`FoodDishServiceTest` and `FoodDishServiceTestUtil`).

**Comment by EstebanJesus** [comment]
Hola @nmarulo me gustaría realizar esta tarea, si me la puedes asignar te lo agradezco.

**Comment by nmarulo** [comment]
Hola @EstebanJesus 👋
Como la otra persona no apareció, te la dejo a ti. 👍
