### ISSUE TITLE
Crear test básico para la clase SettingService

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#9]
- Crear para la siguiente clase, su test correspondiente:
    - `SettingService`

Usar como ejemplo el test de la clase `FoodDishService`.

**Comment by thexahmed00** [comment]
i would like to work on this issue @nmarulo  can you assign me

**Comment by nmarulo** [comment]
Hello @thexahmed00  👋
Of course. 

As a clarification, remember that the `FoodDishServiceTest` and `FoodDishServiceTestUtil` classes must be used as references.

**Comment by nmarulo** [comment]
@thexahmed00 please confirm if you are still interested in working on this assignment, thank you.

**Comment by thexahmed00** [comment]
I was busy with production issue i am on it by tomorrow i will snd a PR

**Comment by nmarulo** [comment]
@thexahmed00 ok, don't worry 👍
I usually give a week to make the issue, but since you didn't answer anything after assigning the issue, that's why I asked.

**Comment by thexahmed00** [comment]
![image](https://user-images.githubusercontent.com/58472920/195537222-bf9c401d-96eb-4f1c-b0bd-9f5c750b764a.png)
 exception while running app

**Comment by nmarulo** [comment]
@thexahmed00 
If you run the application in normal mode, you need to have a database configured. [README.en.md#run](https://github.com/npedidos/rest-api/blob/master/translations/README.en.md#run)
If you only run the test, it is not necessary.

**Comment by thexahmed00** [comment]
@nmarulo  api doc how to access

**Comment by nmarulo** [comment]
@thexahmed00 
To access the application you must first fill the database with test records, by executing: [RUN db-seed](https://github.com/npedidos/rest-api/blob/master/translations/README.en.md#db-seed)
Then, in the [login](https://github.com/npedidos/rest-api/blob/master/translations/README.en.md#login) table, valid login users are created.
This information is used to authenticate ([/auth/login](https://www.postman.com/nmarulo/workspace/github/request/3462094-f0a0a48e-28b3-4d94-8fd8-486b2e088de8)) with the local server and generate a JWT token that must be sent in all requests.

**Comment by nmarulo** [comment]
although, if you mean the swagger api doc or using swagger web, just use a user and password from the user table.

**Comment by thexahmed00** [comment]
@nmarulo Sorry bro Not able to understand codebase you can assign to Others

**Comment by nmarulo** [comment]
@thexahmed00 no problem, thank you very much. 🤝

Still, if it is not too much trouble, I would like to know what you have had difficulties with, that would help me to improve the documentation, I know very well that, the current one, is not very clear.

In case you want to give it a last chance, in this issues #19 there are issues that are the same and that other people have done.

**Comment by ArturWood** [comment]
Hello @nmarulo is anyone working on this?

This way I could practice unit tests.

**Comment by nmarulo** [comment]
@ArturWood This project is temporarily on pause. The one I have active is "despensa-rest-api".

**Comment by ArturWood** [comment]
Ok, sorry for the misunderstanding, I found the other repository and contributed, thanks for the reply!
